

name: Smoke Test

on: 
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          yarn install

      - name: Generate OpenAPI Clients
        run: |
          yarn swagger
          
      - name: Compile React app
        run: |
          yarn build

